# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AMapReader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road_base_info',
            name='name',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
    ]
